// SherpaOnnx-Bridging-Header.h
// Bridges sherpa-onnx C-API into Swift. Generated by VoiceInk RU build.
#ifndef SHERPAONNX_BRIDGING_HEADER_H
#define SHERPAONNX_BRIDGING_HEADER_H
#import "sherpa-onnx/c-api/c-api.h"
#endif
